import numpy as np 
a=np.array([2,3,4,5],dtype=float)
print('Array from list',a)
b=np.array((2,3,4,5))
print('Array from tuple',b)
c=np.zeros((3,4))
print('Array with all 0', c)
c=c.reshape((2,2,3))
print('Array reshaped', c)
d=np.arange(0,21,5)
print('SEquence',d)
e=np.arange(12).reshape(3,4)
f=np.max(e)
g=np.min(e)
h=np.sum(e)
i=np.max(e,axis=1)
k=np.max(e,axis=0)
l=np.min(e,axis=0)
j=np.min(e,axis=1)
print('Max element',f)
print('Min element',g)
print('Sum' ,h)
print('Col wise maximum',i)
print('Col wise minimum',j)
print('Row wise maximum',k)
print('Row wise minimum',l)